[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install",
  "cd server && npm install",
  "cd client && npm install"
]

[phases.build]
cmds = [
  "cd client && npm run build",
  "cp -r client/dist/* server/public/"
]

[start]
cmd = "cd server && node index.js"
